# -*- coding: utf-8 -*-
"""

"""

import pathlib
import pandas as pd

class Aggregator():
    def transform_raw_to_stacked(plfa_tools_output: pd.DataFrame) -> pd.DataFrame:
        """Reformats output from PLFA Tools, of a single sample, into proper tabular format
        plfa_tools_output = Output from PLFA Tools of a single worksheet in the form of a Pandas DataFrame
        
        Header names: SampleId, GCRunId, GCFileLoc, ProcessingCode, ProcessMethod, RunDateTime, RT, Response, Ar/Ht, RFact, ECL, Peak Name, Percent, Comment1, Comment2
        """
        
    def read_file(file_path: pathlib.Path) -> pd.DataFrame:
        """Reads a file from PLFA Tools and returns a pandas DataFrame with all data from all worksheets
        file_path = pathlib Path to a xlsx file as produced by PLFA Tools
        """

    def read_dir(dir_path: pathlib.Path) -> pd.DataFrame:
        """Reads a directory path that contains multiple files from PLFA Tools and returns a pandas DataFrame with all data from all files and worksheets
        dir_path = pathlib Path to directory containing one or more xlsx files as produced by PLFA Tools
        """

    def tidy(df: pd.DataFrame) -> pd.DataFrame:
        """Accepts a Pandas DataFrame generated by "read_dir" or "read_file" and returns a new DataFrame in a tidy format
        df = Pandas DataFrame generated by "read_dir" or "read_file"
        """
 